import { Providers } from "./provider";

export const metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* <p>Root layout</p> */}
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
